name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Ставим минимум рантайм-зависимостей, чтобы не тянуть тяжёлые пакеты
      - name: Install minimal runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install "fastapi==0.116.1" "uvicorn[standard]==0.30.1" "pydantic==2.8.2" "SQLAlchemy==2.0.32" requests

      # Простейшая проверка: код импортируется и стартовая точка приложения валидна
      - name: Smoke test (import app)
        run: python -c "import app.main; print('import-ok')"
